parameters:
    akuma_social.facebook.oauth_provider.class: \League\OAuth2\Client\Provider\Facebook
    akuma_social.facebook.oauth_provider.token.class: Akuma\Bundle\SocialBundle\Security\Authentication\Token\FacebookToken
    akuma_social.facebook.api.class: Akuma\Bundle\SocialBundle\Api\FacebookApi
    akuma_social.facebook.auth.class: Akuma\Bundle\SocialBundle\Security\Authentication\Provider\FacebookAuthenticationProvider
    akuma_social.facebook.security.authentication.listener.class: Akuma\Bundle\SocialBundle\Security\Firewall\FacebookAuthenticationListener
    akuma_social.facebook.security.authentication.entry_point.class: Akuma\Bundle\UserBundle\Security\Authentication\EntryPoint\FacebookEntryPoint

services:
    akuma_social.facebook.api:
        public: true
        parent: akuma_social.abstract.api
        class: %akuma_social.facebook.api.class%

    akuma_social.facebook.auth:
        public: false
        parent: akuma_social.abstract.auth
        class: %akuma_social.facebook.auth.class%

    akuma_social.facebook.security.authentication.listener:
        abstract: true
        parent: akuma_social.abstract.security.authentication.listener
        class: %akuma_social.facebook.security.authentication.listener.class%
