services:
#    akuma_social.google.example:
#        class: Akuma\Bundle\SocialBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

parameters:
    akuma_social.google.api.class: Akuma\Bundle\SocialBundle\Api\GoogleApi
    akuma_social.google.auth.class: Akuma\Bundle\SocialBundle\Security\Authentication\Provider\GoogleAuthenticationProvider
    akuma_social.google.security.authentication.listener.class: Akuma\Bundle\SocialBundle\Security\Firewall\GoogleAuthenticationListener
    akuma_social.google.security.authentication.entry_point.class: Akuma\Bundle\UserBundle\Security\Authentication\EntryPoint\GoogleEntryPoint

services:
    akuma_social.google.api:
        public: true
        parent: akuma_social.abstract.api
        class: %akuma_social.google.api.class%

    akuma_social.google.auth:
        public: false
        parent: akuma_social.abstract.auth
        class: %akuma_social.google.auth.class%

    akuma_social.google.security.authentication.listener:
        abstract: true
        parent: akuma_social.abstract.security.authentication.listener
        class: %akuma_social.google.security.authentication.listener.class%

    akuma_social.google.security.authentication.entry_point:
        public: false
        abstract: true
        parent: akuma_social.abstract.security.authentication.entry_point
        class: %akuma_social.google.security.authentication.entry_point.class%
